settings:
  determineRouteBeforeAppMiddleware: true
renderer:
  template_path: '../templates/'
logger:
  name: slim-app
  # active handler
  active_handler: 'raven'
  logs_handlers:
    default:
      # handler to write logs locally
      path: '../logs/app.log'
    raven:
      # sentry handler
      dsn: 'https://b435bc070cef41a3a3c13c3530dfd5f8:8644b6824c8a4c36a0c9b197b953eccd@sentry.io/97389'
db:
  dbType: mysql
  host: localhost
  dbName: test
  charset: utf8
  username: vagrant
  password: vagrant
spotify:
  clientId: '8591df8a71ae4cd7b6547adf9048d464'
  secretId: 'ff05d85649d5455d8966b5897a79e86d'
  redirectUri: 'http://test1.loc/home'