<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Login</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='css/style.css' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <h1>Hello</h1>
        <div>Please enter your username to log in</div>
        <br>
        
        <div class="form">
            <?php if(isset($_POST['error'])){ echo $_POST['error'];}?>
            <form class="register-form" action="signup" method="post">
              <input type="text" name="name" placeholder="name"/>
              <input type="password" name="password" placeholder="password"/>
              <input type="text" name="email" id="email" placeholder="email address"/>
              <button>create</button>
              <p class="message">Already registered? <a href="#">Sign In</a></p>
            </form>
            
            <form class="login-form"  action="signin" method="post">
              <input type="text" name="email" placeholder="email"/>
              <input type="password" name="password" placeholder="password"/>
              <button>login</button>
              <p class="message">Not registered? <a href="#">Create an account</a></p>
            </form>
        </div>
        
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/login.js"></script>
        <script>
        $(document).ready(function(){
            var email = document.getElementById("email");
            email.onchange = function isEmail(email) {
              var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
              return regex.test(email);
            }
        });
        </script>
    </body>
</html>
