<?php  
$user = $_SESSION['user'];
$songinfo = $_SESSION['songinfo'];
?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>My Music</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="css/hover.css" media="all">
        <link rel="stylesheet" href="css/click.css" type="text/css" />
        <link rel="stylesheet" href="css/nav.css">
        <link rel="stylesheet" href="css/tables.css">
        <link href='css/style.css' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/modernizr.custom.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script src="js/jquery.tablesorter.min.js" type="text/javascript"></script>
        <script type="text/javascript" id="js">
            $(document).ready(function() {
                $("table").tablesorter();
                $("#music").trigger("update"); 
                var sorting = [[0,0]];
                $("#music").trigger("sorton",[sorting]);
            });
        </script>
    </head>
    <body>
        <nav id="topnav" class="navbar-fixed-top">
            <div class = "container-fluid">
                <div class="navbar-header">
                    <button style="background-color:#DFDCD7" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span style="background-color:#FFF" class = "icon-bar"></span>
                        <span style="background-color:#FFF" class = "icon-bar"></span>
                        <span style="background-color:#FFF" class = "icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul id="sides" class="nav navbar-nav navbar-left">
                      <li><a href="#">Hello <?php echo $user ?></a></li>
                    </ul>
                    <ul id="navbar-list">
                        <li><a href="home">Home</a></li>
                        <li><a href="#" class="music active">My Music</a></li>
                    </ul>
                    <ul id="sides" class="nav navbar-nav navbar-right">
                      <li><a href="logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <div id="tableContainer" class="tableContainer">  
        <table name="music" id="music" class="tablesorter">
          <thead class="fixedHeader">
            <tr>
              <th class="header" style="width: 155px; cursor:default;">&nbsp;</th>
              <th class="header">Song</th>
              <th class="header">Artist</th> 
              <th class="header">Album</th>
            </tr>
          </thead>
          <tbody class="scrollContent" id="tableBody">
              <?php echo $songinfo ?>
          </tbody>
        </table>
        </div>
    </body>
    <script>
    $(document).ready(function() {
        var saved = "";
        var audio = $("#song")[0];
        $('tr').click(function() {
            if(audio.paused){
                var source = $(this).attr('id');
                $("#song_link").attr("src",source+".mp3");
                audio.load();
                audio.play();
                saved = $("#song_link").attr('src');
            } else {
                audio.pause();
                if( saved !== ($(this).attr('id')+".mp3") ){
                    var source = $(this).attr('id');
                    $("#song_link").attr("src",source+".mp3");
                    audio.load();
                    audio.play();
                    saved = $("#song_link").attr('src');
                }
            }
        });
        
        var form = document.getElementById("musicreg");

        document.getElementById("repeat").addEventListener("click", function () {
          form.submit();
        });
    });
    </script>
</html>
